
import {
    LayoutDashboard,
    Users,
    FileText,
    Settings,
    LogOut,
    Search,
    MessageSquare,
    Mic,
    Phone,
    Globe,
    HeartHandshake,
    Loader2,
    X,
    Check,
    CheckCircle,
    XCircle,
    Clock,
    AlertTriangle,
    ArrowRight,
    Building,
    ArrowLeft,
    Briefcase,
    Home,
    AlertCircle,
    Plus,
    Send,
    MapPin,
    Mail,
    Activity,
    Trash2
} from "lucide-react"

export const Icons = {
    dashboard: LayoutDashboard,
    users: Users,
    resources: FileText,
    settings: Settings,
    logout: LogOut,
    search: Search,
    chat: MessageSquare,
    mic: Mic,
    phone: Phone,
    language: Globe,
    care: HeartHandshake,
    spinner: Loader2,
    close: X,
    check: Check,
    checkCircle: CheckCircle,
    xCircle: XCircle,
    clock: Clock,
    warning: AlertTriangle,
    arrowRight: ArrowRight,
    building: Building,
    arrowLeft: ArrowLeft,
    briefcase: Briefcase,
    home: Home,
    plus: Plus,
    send: Send,
    alertCircle: AlertCircle,
    x: X,
    globe: Globe,
    fileText: FileText,
    heartHandshake: HeartHandshake,
    mapPin: MapPin,
    mail: Mail,
    activity: Activity,
    trash: Trash2
}
